# Generated by Django 4.2.4 on 2023-11-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
